### ISSUE TITLE
Global PSF

### ISSUE THREAD

**Issue by lmowla** [j-hive/morphfits#13]
I noticed that there is a psf file in every object folder. This is not necessary as it is the same PSF used for every object. There should be a global PSF generation at the beginning before we start the processing per object.

**Comment by hansenjiang** [comment]
@lmowla The current PSF crop size is calculated as a ratio between the PSF and science pixscales, multiplied by the cutout size, as follows.
```
psf_image_size = int(cutout_size * psf_pixscale / pixscale)
```
Do we want one fixed size for each filter's PSF?

**Comment by hansenjiang** [comment]
Closing as each PSF accounts for stamp size.
