### ISSUE TITLE
Add filter name to the stdout

### ISSUE THREAD

**Issue by lmowla** [j-hive/morphfits#16]
The progress tracker with messages for every galwrap is fitting is amazing. I was wondering if we can also add the filter name to this message. 
For example, `35m2024-09-18T12:17:33 [34mINFO    [36mGALWRAP     [32mRunning GALFIT for object 13734.` to `35m2024-09-18T12:17:33 [34mINFO    [36mGALWRAP     [32mRunning GALFIT for object 13734 in f150w-clear.`

**Comment by hansenjiang** [comment]
Closed by #29.
